[pytest]

markers =
    searchitem: mark a test as a search item test
    addtocart: Add to cart tests
    validatecart : validate cart tests
    validsearchitem : search items data driven
    invalidsearchitem : test invalid search items
    visibility : homepage visibility tests
    